### ISSUE TITLE
Help me understand the mention scorer...!

### ISSUE THREAD

**Issue by fairy-of-9** [pitrack/incremental-coref#5]
I had a question while looking at your paper and code.

I have been understanding that the mention scorer of e2e-coref gives a one-dimensional value(scalar score) to each span.
But, [here](https://github.com/pitrack/incremental-coref/blob/1790cd0463da51a07b9c3abf440a063f5a63fc75/torch_scores.py#L112) you give 3000 dimensions to the mention score. (According to [config](https://github.com/pitrack/incremental-coref/blob/1790cd0463da51a07b9c3abf440a063f5a63fc75/jsonnets/base.jsonnet#L54)).

Can you tell me if I misunderstand in your paper or code?
Thanks!

**Comment by pitrack** [comment]
Thanks for the great question!

The code is a bit convoluted here. The tl;dr is that for an input embedding x (dim=3092 for large models), we're essentially doing x_1 = relu(W_1 x+b) for W_1 with size (3000, 3092) and b size (3000). Then we're returning (W_2)(x_1) where W_2 has size (1, 3000).

Line by line (comparing with the Joshi et al. repo which is essentially the same as e2e model):

x has dim 3092: [ours](https://github.com/pitrack/incremental-coref/blob/main/torch_scores.py#L73) vs. [theirs](https://github.com/mandarjoshi90/coref/blob/master/independent.py#L371)

relu(W_1 x + b): ours: [note FFNN is a wrapper](https://github.com/pitrack/incremental-coref/blob/main/torch_scores.py#L29)  which calls [util.FFNN](https://github.com/pitrack/incremental-coref/blob/main/util.py#L232) and [theirs](https://github.com/mandarjoshi90/coref/blob/master/independent.py#L377) is also a wrapper calling an even more general [util.FFNN](https://github.com/mandarjoshi90/coref/blob/master/util.py#L109)

You've observed that our W_1 has dim (3092, 3000). [Theirs](https://github.com/mandarjoshi90/coref/blob/master/experiments.conf#L115) does too.

Finally, both models have a projection. Note that when the wrapper is called, both functions hardcode/pass in `output_dim=1`  or `output_size=1`. This triggers a conditional projections for [ours](https://github.com/pitrack/incremental-coref/blob/main/util.py#L222) but and it's a mandatory argument for [theirs](https://github.com/mandarjoshi90/coref/blob/master/util.py#L115).

Anyway, I hope this clears things up and let me know if you have more questions. Thanks for making me check because when I read your question I also forgot about this and was confused/worried too 😅

**Comment by fairy-of-9** [comment]
Everything has become clear!!
Thank you for providing good answer, paper and codes 😀
